version: "3.8"
services:
  cookbookr-db:
    container_name: cookbookr-db
    restart: unless-stopped
    volumes:
      - "cookbookr-store:/postgres"
    image: "postgres"
  cheffer-redis:
    container_name: cheffer-redis
    restart: unless-stopped
    volumes:
      - "cheffer-store:/data"
    image: redis
  cheffer:
    container_name: cheffer
    restart: unless-stopped
    image: ghcr.io/nickyg91/recipe-crawler:main
    ports:
      - "8084:80"
    volumes:
      - "/opt:/opt"
    depends_on:
      - cheffer-redis
      - cookbookr-db
volumes:
  cheffer-store:
  cookbookr-store:
